## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [3]:
import tensorflow as tf

In [0]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default


### Collect Data

In [4]:
from google.colab import drive
drive.mount('/edrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
import pandas as pd

In [0]:
dataset1 = pd.read_csv('/edrive/My Drive/residency6/prices.csv')

### Check all columns in the dataset

In [135]:
dataset1.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [136]:
dataset1.shape

(851264, 7)

### Drop columns `date` and  `symbol`

In [137]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


In [0]:
dataset2=dataset1.drop(["date","symbol"],axis=1)

In [139]:
dataset2.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [140]:
dataset2.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [0]:
dataset3=dataset2.head(1000)

In [142]:
dataset3.shape

(1000, 5)

In [199]:
dataset3["volume"]=dataset3["volume"]/1000000

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [200]:
dataset3.head()

open       close         low        high  volume
0  123.430000  125.839996  122.309998  126.250000  2.1636
1  125.239998  119.980003  119.940002  125.540001  2.3864
2  116.379997  114.949997  114.930000  119.739998  2.4895
3  115.480003  116.620003  113.500000  117.440002  2.0063
4  117.010002  114.970001  114.089996  117.330002  1.4086

### Divide the data into train and test sets

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
tf.enable_eager_execution()

In [0]:
x=dataset3.drop(["volume"],axis=1)
y=dataset3["volume"]

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

#### Convert Training and Test Data to numpy float32 arrays


In [0]:
import numpy as np
x_train=np.array(x_train).astype(np.float32)
x_test=np.array(x_test).astype(np.float32)

In [0]:
y_train=np.array(y_train).astype(np.float32)
y_test=np.array(y_test).astype(np.float32)

In [207]:
x_train.dtype

dtype('float32')

In [208]:
y_test.dtype

dtype('float32')

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [0]:
from sklearn.preprocessing import normalize

In [0]:
x_train1=normalize(x_train)

In [211]:
x_train1

array([[0.49503326, 0.50456154, 0.49442136, 0.5058727 ],
       [0.49014246, 0.5128518 , 0.48143727, 0.5147442 ],
       [0.49802995, 0.50234187, 0.495874  , 0.5037139 ],
       ...,
       [0.49995428, 0.5016043 , 0.49572614, 0.5026871 ],
       [0.49740046, 0.5029231 , 0.49371874, 0.50586843],
       [0.50012493, 0.5005309 , 0.49594367, 0.5033725 ]], dtype=float32)

In [0]:
x_test1=normalize(x_test)


## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [0]:
#We are initializing weights and Bias with Zero
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

2.Define a function to calculate prediction

In [0]:
def prediction(x1, w, b):
    
    xw_matmul = tf.matmul(x1, w)
    y_out = tf.add(xw_matmul, b)
    
    return y_out
    

3.Loss (Cost) Function [Mean square error]

In [0]:

def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x1, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x1, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [218]:
#Train for 100 Steps
for i in range(100):
    
    w, b = train(x_train1,y_train, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, 
          loss(y_train, prediction(x_train1, w, b)).numpy())

('Current Loss on iteration', 0, 205.55208)
('Current Loss on iteration', 1, 203.65453)
('Current Loss on iteration', 2, 201.90575)
('Current Loss on iteration', 3, 200.29407)
('Current Loss on iteration', 4, 198.80875)
('Current Loss on iteration', 5, 197.43985)
('Current Loss on iteration', 6, 196.1783)
('Current Loss on iteration', 7, 195.01566)
('Current Loss on iteration', 8, 193.94412)
('Current Loss on iteration', 9, 192.95662)
('Current Loss on iteration', 10, 192.04655)
('Current Loss on iteration', 11, 191.2078)
('Current Loss on iteration', 12, 190.43483)
('Current Loss on iteration', 13, 189.72244)
('Current Loss on iteration', 14, 189.06592)
('Current Loss on iteration', 15, 188.46085)
('Current Loss on iteration', 16, 187.90323)
('Current Loss on iteration', 17, 187.38933)
('Current Loss on iteration', 18, 186.91573)
('Current Loss on iteration', 19, 186.47922)
('Current Loss on iteration', 20, 186.07695)
('Current Loss on iteration', 21, 185.7062)
('Current Loss on itera

### Get the shapes and values of W and b

In [219]:
w.shape

TensorShape([Dimension(4), Dimension(1)])

In [220]:
w

<tf.Tensor: id=14218, shape=(4, 1), dtype=float32, numpy=
array([[1.25822  ],
       [1.2619466],
       [1.244955 ],
       [1.2729903]], dtype=float32)>

In [221]:
b.shape

TensorShape([Dimension(1)])

In [222]:
b

<tf.Tensor: id=14221, shape=(1,), dtype=float32, numpy=array([2.5191956], dtype=float32)>

### Model Prediction on 1st Examples in Test Dataset

In [223]:
np.expand_dims(x_test1[0], axis=0).shape

(1, 4)

In [0]:
pred=prediction(x_test1[0:1], w, b).numpy()

In [225]:
pred

array([[5.0383167]], dtype=float32)

In [227]:
loss(y_test[0:1],prediction(x_test1[0:1], w, b)).numpy()

17.263332

dtype('float32')

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

In [0]:
df = pd.read_csv('Iris.csv')

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [230]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [233]:

# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
df['Species']= label_encoder.fit_transform(df['Species']) 
  
df['Species'].unique() 


array([0, 1, 2])

In [234]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [0]:
df1=pd.get_dummies(df,columns=["Species"])

In [250]:
df1.head()

Id  SepalLengthCm  SepalWidthCm  ...  Species_0  Species_1  Species_2
0   1            5.1           3.5  ...          1          0          0
1   2            4.9           3.0  ...          1          0          0
2   3            4.7           3.2  ...          1          0          0
3   4            4.6           3.1  ...          1          0          0
4   5            5.0           3.6  ...          1          0          0

[5 rows x 8 columns]

### Splitting the data into feature set and target set

In [0]:
x_df1=df1.drop(["Id","Species_0","Species_1","Species_2"],axis=1)
y_df1=df1[["Species_0","Species_1","Species_2"]]

In [0]:
X_train,X_test,Y_train,Y_test=train_test_split(x_df1,y_df1,test_size=0.2)

In [267]:
X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
122            7.7           2.8            6.7           2.0
13             4.3           3.0            1.1           0.1
32             5.2           4.1            1.5           0.1
21             5.1           3.7            1.5           0.4
40             5.0           3.5            1.3           0.3
99             5.7           2.8            4.1           1.3
7              5.0           3.4            1.5           0.2
1              4.9           3.0            1.4           0.2
84             5.4           3.0            4.5           1.5
89             5.5           2.5            4.0           1.3
112            6.8           3.0            5.5           2.1
125            7.2           3.2            6.0           1.8
35             5.0           3.2            1.2           0.2
147            6.5           3.0            5.2           2.0
42             4.4           3.2            1.3           0.2
44             5.1           3.8            1.9           0.4
94             5.6           2.7            4.2           1.3
110            6.5           3.2            5.1           2.0
85             6.0           3.4            4.5           1.6
67             5.8           2.7            4.1           1.0
75             6.6           3.0            4.4           1.4
60             5.0           2.0            3.5           1.0
115            6.4           3.2            5.3           2.3
71             6.1           2.8            4.0           1.3
77             6.7           3.0            5.0           1.7
95             5.7           3.0            4.2           1.2
113            5.7           2.5            5.0           2.0
68             6.2           2.2            4.5           1.5
142            5.8           2.7            5.1           1.9
39             5.1           3.4            1.5           0.2
..             ...           ...            ...           ...
108            6.7           2.5            5.8           1.8
136            6.3           3.4            5.6           2.4
140            6.7           3.1            5.6           2.4
29             4.7           3.2            1.6           0.2
14             5.8           4.0            1.2           0.2
2              4.7           3.2            1.3           0.2
57             4.9           2.4            3.3           1.0
59             5.2           2.7            3.9           1.4
123            6.3           2.7            4.9           1.8
74             6.4           2.9            4.3           1.3
66             5.6           3.0            4.5           1.5
11             4.8           3.4            1.6           0.2
27             5.2           3.5            1.5           0.2
149            5.9           3.0            5.1           1.8
41             4.5           2.3            1.3           0.3
144            6.7           3.3            5.7           2.5
47             4.6           3.2            1.4           0.2
127            6.1           3.0            4.9           1.8
56             6.3           3.3            4.7           1.6
8              4.4           2.9            1.4           0.2
55             5.7           2.8            4.5           1.3
131            7.9           3.8            6.4           2.0
118            7.7           2.6            6.9           2.3
0              5.1           3.5            1.4           0.2
3              4.6           3.1            1.5           0.2
128            6.4           2.8            5.6           2.1
139            6.9           3.1            5.4           2.1
117            7.7           3.8            6.7           2.2
104            6.5           3.0            5.8           2.2
6              4.6           3.4            1.4           0.3

[120 rows x 4 columns]

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function 

In [0]:


model = tf.keras.models.Sequential()



#add model layers
model.add(tf.keras.layers.Dense(3, input_shape=(4,),activation='softmax'))


In [0]:
#complie the model 
model.compile(optimizer='sgd', loss='categorical_crossentropy', 
              metrics=['accuracy'])

### Model Training 

In [270]:
model.fit(X_train,Y_train,          
          validation_data=(X_test,Y_test),
          epochs=100,
          batch_size=32)

W1103 12:12:37.477353 140144041236352 training.py:503] Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <type 'NoneType'>
W1103 12:12:37.558943 140144041236352 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 120 samples, validate on 30 samples
Epoch 1/100
120/120 [==============================] - 0s 2ms/sample - loss: 7.1625 - acc: 0.3417 - val_loss: 6.7475 - val_acc: 0.3000
Epoch 2/100
120/120 [==============================] - 0s 124us/sample - loss: 5.8115 - acc: 0.3417 - val_loss: 5.5681 - val_acc: 0.3000
Epoch 3/100
120/120 [==============================] - 0s 135us/sample - loss: 4.7966 - acc: 0.3417 - val_loss: 4.7078 - val_acc: 0.3000
Epoch 4/100
120/120 [==============================] - 0s 122us/sample - loss: 4.0487 - acc: 0.3417 - val_loss: 4.1036 - val_acc: 0.3000
Epoch 5/100
120/120 [==============================] - 0s 123us/sample - loss: 3.5364 - acc: 0.3417 - val_loss: 3.6711 - val_acc: 0.2333
Epoch 6/100
120/120 [==============================] - 0s 116us/sample - loss: 3.1884 - acc: 0.2583 - val_loss: 3.3350 - val_acc: 0.1000
Epoch 7/100
120/120 [==============================] - 0s 128us/sample - loss: 2.9076 - acc: 0.1167 - val_loss: 3.0189 - val_acc: 0.066

### Model Prediction

In [272]:
#Model prediction
prediction = model.predict(X_test)

#Print prediction
print(prediction)

W1103 12:13:47.075778 140144041236352 training.py:503] Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <type 'NoneType'>


[[0.01638924 0.41258666 0.5710241 ]
 [0.06581663 0.41024265 0.5239407 ]
 [0.83402747 0.11308996 0.05288265]
 [0.8790499  0.08117566 0.03977445]
 [0.7676849  0.1537056  0.0786095 ]
 [0.08641391 0.4135815  0.5000046 ]
 [0.18023391 0.40057522 0.41919088]
 [0.00970173 0.47882146 0.5114768 ]
 [0.8925524  0.07801453 0.02943304]
 [0.01112871 0.46715048 0.5217208 ]
 [0.8551923  0.09255672 0.0522509 ]
 [0.86167544 0.09120005 0.04712456]
 [0.10715192 0.41100764 0.4818404 ]
 [0.01194431 0.31206232 0.6759933 ]
 [0.02638213 0.34026235 0.63335556]
 [0.0244054  0.49772817 0.4778664 ]
 [0.07949421 0.3886858  0.53182   ]
 [0.03194223 0.4462017  0.52185607]
 [0.13347691 0.39605704 0.470466  ]
 [0.8251019  0.1092604  0.06563767]
 [0.798474   0.13373843 0.06778764]
 [0.8536469  0.09242607 0.05392697]
 [0.02584316 0.37901163 0.5951452 ]
 [0.01825771 0.3855388  0.5962035 ]
 [0.00449274 0.42124954 0.5742577 ]
 [0.15618122 0.4473282  0.39649063]
 [0.0191776  0.3829876  0.59783477]
 [0.8671931  0.08919588 0.04

### Save the Model

In [0]:
model.save('Lab6_internal_Iris.h5')

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?